Try to fix failing build

diff --git a/.github/workflows/build-apps.yml b/.github/workflows/build-apps.yml
--- a/.github/workflows/build-apps.yml
+++ b/.github/workflows/build-apps.yml
@@ -20,6 +20,13 @@ jobs:
             exit 1
           fi      
 
+      - name: Check for GOOGLE_SERVICE_ACCOUNT_JSON
+        run: |
+          if [ -z "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" ]; then
+            echo "You must provide a GOOGLE_SERVICE_ACCOUNT_JSON secret in this repo's secrets."
+            exit 1
+          fi
+
       - name: Checkout code
         uses: actions/checkout@v3
 
@@ -40,6 +47,16 @@ jobs:
         run: |
           cd mobile
           npm install --legacy-peer-deps
+
+      - name: Write Google service account file and check if it has contents
+        run: echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}' > ./mobile/google-service-account.json
+              if [ ! -f "./mobile/google-service-account.json" ]; then
+                echo "Failed to create the google-service-account.json file"
+                exit 1
+              elif [ ! -s "./mobile/google-service-account.json" ]; then
+                echo "The google-service-account.json file is empty"
+                exit 1
+              fi
 
       - name: Run script
         run: |
